server:
  port: 8082

spring:
  application: ecommerce-order-service

  datasource:
    url: jdbc:pgsql://${DB_HOST}:${DB_PORT}/ecommerce-order-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: "*"