server:
  port: 8082

spring:
  application: ecommerce-order-service

  datasource:
    url: jdbc:pgsql://${DB_HOST:localhost}:${DB_PORT:5432}/ecommerce-order-db
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

#  cloud:
#    config:
#      uri: http://localhost:8888

  config:
    import: configserver:http://localhost:8888/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"